### ISSUE TITLE
尝试分析一个so文件时，出现的一些问题，希望能提供帮助或意见

### ISSUE THREAD

**Issue by TopCode280** [pcy190/deobfuscator#5]
使用analyzer.py去分析libmsaoaidsec.so文件
if __name__ == '__main__':
    # load_to_angr('example/lib64_example.so', 0x13C88)
    analyzer = DeflatAnalyzer('example/libmsaoaidsec.so')
    analyzer.analysis_flatten_blocks(0xC40C)
    analyzer.show_blocks_info()
以下是异常日志
CRITICAL | 2023-07-06 16:23:57,481 | cle.backends.backend | Deprecation warning: the custom_base_addr parameter has been renamed to base_addr
WARNING  | 2023-07-06 16:23:57,864 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __stack_chk_guard
WARNING  | 2023-07-06 16:23:57,864 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __sF
WARNING  | 2023-07-06 16:23:57,868 | cle.loader     | For more information about "Symbol was allocated without a known size",see https://docs.angr.io/extending-angr/environment#simdata
WARNING  | 2023-07-06 16:24:08,360 | pyvex.lifting.gym.arm_spotter | Ignoring STMxx ^ instruction at 0x17518. This mode is not implemented by VEX! See pyvex/lifting/gym/arm_spotter.py
base addr : 0x0

                [WARNING] start address is higher than base address. 
                Check if the start address has stripped the base address.
                
fail to find function at 0xc40c, now try blocks analysis
是不是因为导入表的函数未找到，需要导入例如libc.so
感谢项目的开源

**Comment by pcy190** [comment]
It depends. Seems that this elf needs to rebased.
