### ISSUE TITLE
Exception: Not a valid binary file: '/example/lib64_example.so'

### ISSUE THREAD

**Issue by KA2010** [pcy190/deobfuscator#6]
File "/home/kawkab/.local/lib/python3.8/site-packages/angr/project.py", line 130, in __init__
    raise Exception("Not a valid binary file: %s" % repr(thing))
Exception: Not a valid binary file: '/example/lib64_example.so'

What might the error?

**Comment by KA2010** [comment]
@pcy190

**Comment by pcy190** [comment]
This repo already contains the file `example/lib64_example.so`. Please check if the path to `lib64_example.so` in your script is correct. Your current path points to an incorrect absolute path.

**Comment by KA2010** [comment]
@pcy190 Thanks for reply, I got it. 
I have another question. Do you have blog post or any documents explain this code?
if not what motivated you using Qiling?
thanks in advance
